repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
